Fixed parameter pollution
418sec/objutil pull request #1
Opened 2020-05-24 14:51 UTC by bbeale

### ⚙️ Description *

`objutil` suffers from a vulnerability that allows arbitrary values to be appended to an object prototype.

### 💻 Technical Description *

Neither the `merge()` function nor it's `_assignHelper()` inside of `objutil.js` perform any validation checks on the arguments other than making sure the `target` is not null. To prevent users from polluting the prototype with arbitrary or malicious values, I added a guard clause to `merge()` that returns an error if \_\_proto\_\_ is found inside `arg`. 

### 🐛 Proof of Concept (PoC) *

```
var a = { x:1,y:{ w:1, z:2 }}
var malicious_payload = '{"__proto__":{"vulnerable":"Polluted"}}';
var {merge, remove} = require('objutil')
result = merge(a,JSON.parse(malicious_payload));
console.log({}.vulnerable);
```

### 🔥 Proof of Fix (PoF) *

```
function merge(target, arg) { // length==2
  if (arg.hasOwnProperty('__proto__'))
    throw new TypeError('Altering the prototype is potentially dangerous and therefore not allowed.')
  return _assignHelper(target, arguments, function (a, b, key, path) {
    var bval = b[key]
    if (bval !== undefined && isPrimitive(bval)) a[key] = bval
    else if (!(key in a)) a[key] = isArray(bval) ? [] : isPOJO(bval) ? {} : bval
  })
}
```

### 👍 User Acceptance Testing (UAT)

Run the following unit test in `test/test.js`

```
it('@ merge with prototype', function () {
  var o1 = { x: 1, y: { w: 1, z: 2 } }
  var o2 = '{ "__proto__": { "vulnerable": "Polluted" } }'
  try {
    var obj = lib.merge(o1, JSON.parse(o2))
  } catch (e) {
    expect(e).to.be.an('error')
  }
})
```

2020-06-10 14:22 UTC, toufik-airane requested changes
Dear @bbeale,

It's an awesome contribution.
However, I've some concerned about possible bypasses using:
```
'{"contructor": {"prototype": {"key": value}}}';
```
What do you think? Can you take care of it?

### Resource
https://snyk.io/vuln/SNYK-JS-OBJUTIL-559496
https://itnext.io/prototype-pollution-attack-on-nodejs-applications-94a8582373e7
CVE-2019–10744

Thank you.

2020-06-10 15:57 UTC, bbeale commented
No problem at all @toufik-airane, I will take another look at it this afternoon and address your concern.

2020-06-11 02:39 UTC, bbeale commented
@toufik-airane updated my PR to check for 'proto' anywhere in that JSON string being merged. Please let me know what you think.

2020-06-11 08:38 UTC, toufik-airane approved these changes
Beautiful!

![huntr](https://img.shields.io/badge/LGTM-red?labelColor=black&link=https://www.huntr.dev&style=flat-square&label=&logo=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAfQAAAH0BAMAAAA5+MK5AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAFVBMVEVHcEzUTjrUSz7bUUXfTj/eTD3wWkwE37jxAAAABnRSTlMAOsPzjWJ73M2lAAAJoElEQVR42u2dS0PbOhBGLb/W4eU1hdbrtIDXAVKv01K8DjHo//+EC5RbHNsQSbHs0eg76yblRLI0I43kIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAECbg4OZl97H5/KZzU/v7JNcvlFf+2V+KBtc+WR+J7d49NbcI/dD2cGTPh/LHr74YC6KPvV65YF6JXt59LS7+9Hli4/Ua+5h3ZH8kCcfx7g3eI902SfmvEc6IT9l4Wujs272HY3O+Wk/2qXOd5AvpK/NHu00lw9M1fPd6kxDulgqcOpTyubD/CaV4DjQhWrqHAe6Uk1942EkxzeQj1TV+fX4XFW95maeSOlrj4/U1bn1+FJdnVmPF1L62uMjHXVePb7SUecV1UgtOMXxsZ76nJF6pjG+f/tzzmmJLtdo8noVCE+nNrnhtEgV6j3qnPp7pafOaYEu11TnM7EnUpe5p486p2bPtNXZPO25vjqT5XghDeARxscm6jwGutREnUdYU5qo8xjjCxN1ySGQT4zMWSzQhWbqaz8DGi7jXGmmvvF2lOMwzglDcwbjXGyq7n48l5qqu78H87o4VUsfk7eXAf7SZJR3f8P1WeJ76OUQL15OLuZeDvHh8zMb+jnER5uZYaM7H8VnC+OZ3fUh/l5/74VPFG8cyUrn1SNjdecTmFz6msB8sD51cbZcLu/vl8ubm/OC6+zWVfrx81drOPhzUzCc3Tr9/Wv/I/z3hh5OuZtQE3+VL3hN7Nv9vf716T++ZTWxV1oFQoecJvatDrx7oj7kox7rFoUdsYlpUu0t85JLTFNqX76SMCkrEQbD9REP9dhAQ/AI50KTOTpjoR6ZpCIJC/XUaJ7KOQTxqVE4nnHYY8+Mum7MSl0vOOGQumVm0XjOSF0z/awYZK2V2UObMmj1ymyCDhm1+lzvYzGjVtfMQxIGrZ6ZqQtG6gszdQ6T2wrqmuGcy4Fsul+re6geMEhaw/2GuTXUXSTeb16f+6eeMFqHN4zhFwzUDTO3lcPqgZl6xGG7MTeaoFMOm8ylUTCecaiIr/ZZm3O7oCTbZ0XW7VN+ZgMWi+Ixo0hWsCgZjE1imphBMPfegA8mT8nCafVgn53WmdvqucEUXfI4ClAZtCCTAyAGK/EJk2M/kf44FzEphzfYPquYHIIQ+nVEBZez+9olgwm7A08Puo+6+4e4tYtDSjZH91PNa9QEnwsbQk2VkM81HUKzQLhicrbx5LpxJc9K65d6HuCX7o7xJ+cvTV1q9fjo/ZaO52jocuWkeHL7t6kzrStHyvf62NcPuij/+/+mDnUOQsSNWvi3iOCbY90+Lv4NbonOQc33E4Gn/z5XX7tkftc84lWoH95qnHuZNe6pu3Sm4UW+dRy5VG/2rHFWpvklm5Vjnf1tcMuUz+w1Gv2pda+JE53+uH39c6h8LLtx9nfdvpfxG33zw871MkL1vGLzYON15yD/FXXznhfwrnLFI73N46w933PlnLl8qtQuYWj2l03f3RVXTvX2V34r3biS7L5/8zvhsf2DG5WU3r+rcn/NF6rmCu32cfJ6p3TzINVMVvHeoUdjc7Kvw1H863vdlT/75NCD3uvebrtbty+m0nqF1VZcmuh8lOAm5JHerWKX/y7nEbd6nyQ3wwntW7E3X+8PDu6X59r3y1Ib6QxvgWdwo7J+o5tDrNkjOSKnzg7ve0NqkI/lqKz8HOSoDXTFuOqE9p8TOTIzP8d3WmN8Nbb6g59TG62HfWxzOiVGo49ydCqH4/HVV74O8HSGeI/V0/HV535G8JQKxtvql/e/Dgbl5OSGqHo1wk74Mc1wrmxHWgcHs5nd35fKTkTe2iN47qLDp1aCZCRbbP9RQvw5+2J5RKGyRtWedsKLix/LJjdnZ2dfl3vwsx0z1hTVV4G4qy+GXra5av83RNbgW82RWAraS3rqSeshtBLXPrTGeBpLVHFr1rES3D22vpdG6ha21EtL2w4pvW32SdRppG5RS70aQ51G6pZ+9kzaetZp5C8Z1EdVp5G6Va1n0op6e9KkkbqVnw1HA6pX9FK3fAz1h27vIqhuK5At6anLKdQlPfXakvqaorpoq4eW1HNy1QVJeyNwHHUKqVs8jfqCorqVjdd5W51C6haOpV6Q23WL2sVN/qino6iftstWKKRuWVs98VV9NZI6hdStaqsLO+qCnnprFXJhR73ztY/+qlNI3fJR1DvPEYUNx13j0VDqCb2qQX/VxTjq3XBh+qw16aoXVtRjcrWiya5gexi6WdH0WWu8K7EeSj0kVysaTqU+feoWTaU+ff6SQv3DVeNB6FnonX7DMRtLPZLUUrdq1zbJUEUVkaSWulU79gXt1JOQSN3KqdSnT93yHRvhgxVVpJJa/lLsKH+wU09CQl3lj7SjPnXqJsZR7+tLK2rqm9HUp07dEoWx2EIVEYXULR5HvW/KnDp1CxXiLhulNATUI4Vo25L62g/1vqRo6tQtVUgvbdSTEEjdMoVFBUvqU6duFdQtq8971KfOWkuFFXMbpTQEstZcYZ/Ekrr0Q713J4+geuKHeqmwHWxJvSaoLmyoC3Lq1e6qFyulNAQmt8xf9VSpbw5fRUQgmovUBuPhS2mmT1/C6dSnzteTcdT7goWpV2mEWsw5fBURgYqSYhT1vpxo6nX43oXS3IJ6SC2O7Znd1iOpT7/JHE6lPn1VhRhDve7/ialtsK8tVJT0rXAvplfPJlKf3rwz69ioIyJZRdSd2W0U0/TsYZK4p6OyX0zTo74I6PV4G8U03XoFInft5dbVu1UqRK4UPbJeTNP9zgUNdTG+OplXv2S2K0o6Q+eainoyuvosoNjsNtTbsQKhd940X+xlo46oHSHSafStvKq2r07rRX6lVfXtRJjYG0vfu7yNOqJt9dOAFrHNipItdXqvaj0aSZ3iC3rv7Kk3V3lXAUFKa3VEjbX9RUCSO1vFNO/q1wFRfltS/7ePR9Y8CI6Llw6fWFKvVwFhxO2VHfXn3/RyFpBHWFC/q6+DwEP1ReAKUB+ynsQZoD5gPQnU6VNAfbiiCmfIoQ51qO9TT+IMA1eUbBxSH3ir9dEh9YHXJeeBrw97PXNJPTm/GI5VAAAAFDm5H4KZg+YDRXQb99wHi2q+O6de+RjFDh3PQR3qUPditWLjnPpgZYMPzqmLodbiHUxZk7NBuA4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAU/wGK2a+A3NJU1QAAAABJRU5ErkJggg==)

2020-06-12 00:16 UTC, mufeedvh commented
Good fix but how about just sanitizing the input `Object` and complete the process?

If the input tries to modify the prototype, your fix will throw a `TypeError`:

```javascript
if (arg.hasOwnProperty('__proto__'))
    throw new TypeError('Altering the prototype is potentially dangerous and therefore not allowed.')
```

Not a bad implementation but there is a better solution. You can freeze the prototype with the **ES5** introduced function [`Object.freeze()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/freeze) which prevents any modifications to an Object's prototype. This is a better solution because it can continue execution without throwing an error and also preventing the vulnerability.

For reference, you can check out this amazing [Paper on Prototype Pollution Attacks & It's Mitigations](https://github.com/HoLyVieR/prototype-pollution-nsec18/blob/master/paper/JavaScript_prototype_pollution_attack_in_NodeJS.pdf)!

![huntr sheriff](https://img.shields.io/badge/SHERIFF-red?labelColor=black&link=https://www.huntr.dev&style=flat-square&logo=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAfQAAAH0BAMAAAA5+MK5AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAFVBMVEVHcEzUTjrUSz7bUUXfTj/eTD3wWkwE37jxAAAABnRSTlMAOsPzjWJ73M2lAAAJoElEQVR42u2dS0PbOhBGLb/W4eU1hdbrtIDXAVKv01K8DjHo//+EC5RbHNsQSbHs0eg76yblRLI0I43kIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAECbg4OZl97H5/KZzU/v7JNcvlFf+2V+KBtc+WR+J7d49NbcI/dD2cGTPh/LHr74YC6KPvV65YF6JXt59LS7+9Hli4/Ua+5h3ZH8kCcfx7g3eI902SfmvEc6IT9l4Wujs272HY3O+Wk/2qXOd5AvpK/NHu00lw9M1fPd6kxDulgqcOpTyubD/CaV4DjQhWrqHAe6Uk1942EkxzeQj1TV+fX4XFW95maeSOlrj4/U1bn1+FJdnVmPF1L62uMjHXVePb7SUecV1UgtOMXxsZ76nJF6pjG+f/tzzmmJLtdo8noVCE+nNrnhtEgV6j3qnPp7pafOaYEu11TnM7EnUpe5p486p2bPtNXZPO25vjqT5XghDeARxscm6jwGutREnUdYU5qo8xjjCxN1ySGQT4zMWSzQhWbqaz8DGi7jXGmmvvF2lOMwzglDcwbjXGyq7n48l5qqu78H87o4VUsfk7eXAf7SZJR3f8P1WeJ76OUQL15OLuZeDvHh8zMb+jnER5uZYaM7H8VnC+OZ3fUh/l5/74VPFG8cyUrn1SNjdecTmFz6msB8sD51cbZcLu/vl8ubm/OC6+zWVfrx81drOPhzUzCc3Tr9/Wv/I/z3hh5OuZtQE3+VL3hN7Nv9vf716T++ZTWxV1oFQoecJvatDrx7oj7kox7rFoUdsYlpUu0t85JLTFNqX76SMCkrEQbD9REP9dhAQ/AI50KTOTpjoR6ZpCIJC/XUaJ7KOQTxqVE4nnHYY8+Mum7MSl0vOOGQumVm0XjOSF0z/awYZK2V2UObMmj1ymyCDhm1+lzvYzGjVtfMQxIGrZ6ZqQtG6gszdQ6T2wrqmuGcy4Fsul+re6geMEhaw/2GuTXUXSTeb16f+6eeMFqHN4zhFwzUDTO3lcPqgZl6xGG7MTeaoFMOm8ylUTCecaiIr/ZZm3O7oCTbZ0XW7VN+ZgMWi+Ixo0hWsCgZjE1imphBMPfegA8mT8nCafVgn53WmdvqucEUXfI4ClAZtCCTAyAGK/EJk2M/kf44FzEphzfYPquYHIIQ+nVEBZez+9olgwm7A08Puo+6+4e4tYtDSjZH91PNa9QEnwsbQk2VkM81HUKzQLhicrbx5LpxJc9K65d6HuCX7o7xJ+cvTV1q9fjo/ZaO52jocuWkeHL7t6kzrStHyvf62NcPuij/+/+mDnUOQsSNWvi3iOCbY90+Lv4NbonOQc33E4Gn/z5XX7tkftc84lWoH95qnHuZNe6pu3Sm4UW+dRy5VG/2rHFWpvklm5Vjnf1tcMuUz+w1Gv2pda+JE53+uH39c6h8LLtx9nfdvpfxG33zw871MkL1vGLzYON15yD/FXXznhfwrnLFI73N46w933PlnLl8qtQuYWj2l03f3RVXTvX2V34r3biS7L5/8zvhsf2DG5WU3r+rcn/NF6rmCu32cfJ6p3TzINVMVvHeoUdjc7Kvw1H863vdlT/75NCD3uvebrtbty+m0nqF1VZcmuh8lOAm5JHerWKX/y7nEbd6nyQ3wwntW7E3X+8PDu6X59r3y1Ib6QxvgWdwo7J+o5tDrNkjOSKnzg7ve0NqkI/lqKz8HOSoDXTFuOqE9p8TOTIzP8d3WmN8Nbb6g59TG62HfWxzOiVGo49ydCqH4/HVV74O8HSGeI/V0/HV535G8JQKxtvql/e/Dgbl5OSGqHo1wk74Mc1wrmxHWgcHs5nd35fKTkTe2iN47qLDp1aCZCRbbP9RQvw5+2J5RKGyRtWedsKLix/LJjdnZ2dfl3vwsx0z1hTVV4G4qy+GXra5av83RNbgW82RWAraS3rqSeshtBLXPrTGeBpLVHFr1rES3D22vpdG6ha21EtL2w4pvW32SdRppG5RS70aQ51G6pZ+9kzaetZp5C8Z1EdVp5G6Va1n0op6e9KkkbqVnw1HA6pX9FK3fAz1h27vIqhuK5At6anLKdQlPfXakvqaorpoq4eW1HNy1QVJeyNwHHUKqVs8jfqCorqVjdd5W51C6haOpV6Q23WL2sVN/qino6iftstWKKRuWVs98VV9NZI6hdStaqsLO+qCnnprFXJhR73ztY/+qlNI3fJR1DvPEYUNx13j0VDqCb2qQX/VxTjq3XBh+qw16aoXVtRjcrWiya5gexi6WdH0WWu8K7EeSj0kVysaTqU+feoWTaU+ff6SQv3DVeNB6FnonX7DMRtLPZLUUrdq1zbJUEUVkaSWulU79gXt1JOQSN3KqdSnT93yHRvhgxVVpJJa/lLsKH+wU09CQl3lj7SjPnXqJsZR7+tLK2rqm9HUp07dEoWx2EIVEYXULR5HvW/KnDp1CxXiLhulNATUI4Vo25L62g/1vqRo6tQtVUgvbdSTEEjdMoVFBUvqU6duFdQtq8971KfOWkuFFXMbpTQEstZcYZ/Ekrr0Q713J4+geuKHeqmwHWxJvSaoLmyoC3Lq1e6qFyulNAQmt8xf9VSpbw5fRUQgmovUBuPhS2mmT1/C6dSnzteTcdT7goWpV2mEWsw5fBURgYqSYhT1vpxo6nX43oXS3IJ6SC2O7Znd1iOpT7/JHE6lPn1VhRhDve7/ialtsK8tVJT0rXAvplfPJlKf3rwz69ioIyJZRdSd2W0U0/TsYZK4p6OyX0zTo74I6PV4G8U03XoFInft5dbVu1UqRK4UPbJeTNP9zgUNdTG+OplXv2S2K0o6Q+eainoyuvosoNjsNtTbsQKhd940X+xlo46oHSHSafStvKq2r07rRX6lVfXtRJjYG0vfu7yNOqJt9dOAFrHNipItdXqvaj0aSZ3iC3rv7Kk3V3lXAUFKa3VEjbX9RUCSO1vFNO/q1wFRfltS/7ePR9Y8CI6Llw6fWFKvVwFhxO2VHfXn3/RyFpBHWFC/q6+DwEP1ReAKUB+ynsQZoD5gPQnU6VNAfbiiCmfIoQ51qO9TT+IMA1eUbBxSH3ir9dEh9YHXJeeBrw97PXNJPTm/GI5VAAAAFDm5H4KZg+YDRXQb99wHi2q+O6de+RjFDh3PQR3qUPditWLjnPpgZYMPzqmLodbiHUxZk7NBuA4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAU/wGK2a+A3NJU1QAAAABJRU5ErkJggg==)

2020-06-12 00:17 UTC, mufeedvh reviewed
Good fix but how about just sanitizing the input `Object` and complete the process?

If the input tries to modify the prototype, your fix will throw a `TypeError`:

```javascript
if (arg.hasOwnProperty('__proto__'))
    throw new TypeError('Altering the prototype is potentially dangerous and therefore not allowed.')
```

Not a bad implementation but there is a better solution. You can freeze the prototype with the **ES5** introduced function [`Object.freeze()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/freeze) which prevents any modifications to an Object's prototype. This is a better solution because it can continue execution without throwing an error and also preventing the vulnerability.

For reference, you can check out this amazing [Paper on Prototype Pollution Attacks & It's Mitigations](https://github.com/HoLyVieR/prototype-pollution-nsec18/blob/master/paper/JavaScript_prototype_pollution_attack_in_NodeJS.pdf)!

![huntr sheriff](https://img.shields.io/badge/SHERIFF-red?labelColor=black&link=https://www.huntr.dev&style=flat-square&logo=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAfQAAAH0BAMAAAA5+MK5AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAFVBMVEVHcEzUTjrUSz7bUUXfTj/eTD3wWkwE37jxAAAABnRSTlMAOsPzjWJ73M2lAAAJoElEQVR42u2dS0PbOhBGLb/W4eU1hdbrtIDXAVKv01K8DjHo//+EC5RbHNsQSbHs0eg76yblRLI0I43kIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAECbg4OZl97H5/KZzU/v7JNcvlFf+2V+KBtc+WR+J7d49NbcI/dD2cGTPh/LHr74YC6KPvV65YF6JXt59LS7+9Hli4/Ua+5h3ZH8kCcfx7g3eI902SfmvEc6IT9l4Wujs272HY3O+Wk/2qXOd5AvpK/NHu00lw9M1fPd6kxDulgqcOpTyubD/CaV4DjQhWrqHAe6Uk1942EkxzeQj1TV+fX4XFW95maeSOlrj4/U1bn1+FJdnVmPF1L62uMjHXVePb7SUecV1UgtOMXxsZ76nJF6pjG+f/tzzmmJLtdo8noVCE+nNrnhtEgV6j3qnPp7pafOaYEu11TnM7EnUpe5p486p2bPtNXZPO25vjqT5XghDeARxscm6jwGutREnUdYU5qo8xjjCxN1ySGQT4zMWSzQhWbqaz8DGi7jXGmmvvF2lOMwzglDcwbjXGyq7n48l5qqu78H87o4VUsfk7eXAf7SZJR3f8P1WeJ76OUQL15OLuZeDvHh8zMb+jnER5uZYaM7H8VnC+OZ3fUh/l5/74VPFG8cyUrn1SNjdecTmFz6msB8sD51cbZcLu/vl8ubm/OC6+zWVfrx81drOPhzUzCc3Tr9/Wv/I/z3hh5OuZtQE3+VL3hN7Nv9vf716T++ZTWxV1oFQoecJvatDrx7oj7kox7rFoUdsYlpUu0t85JLTFNqX76SMCkrEQbD9REP9dhAQ/AI50KTOTpjoR6ZpCIJC/XUaJ7KOQTxqVE4nnHYY8+Mum7MSl0vOOGQumVm0XjOSF0z/awYZK2V2UObMmj1ymyCDhm1+lzvYzGjVtfMQxIGrZ6ZqQtG6gszdQ6T2wrqmuGcy4Fsul+re6geMEhaw/2GuTXUXSTeb16f+6eeMFqHN4zhFwzUDTO3lcPqgZl6xGG7MTeaoFMOm8ylUTCecaiIr/ZZm3O7oCTbZ0XW7VN+ZgMWi+Ixo0hWsCgZjE1imphBMPfegA8mT8nCafVgn53WmdvqucEUXfI4ClAZtCCTAyAGK/EJk2M/kf44FzEphzfYPquYHIIQ+nVEBZez+9olgwm7A08Puo+6+4e4tYtDSjZH91PNa9QEnwsbQk2VkM81HUKzQLhicrbx5LpxJc9K65d6HuCX7o7xJ+cvTV1q9fjo/ZaO52jocuWkeHL7t6kzrStHyvf62NcPuij/+/+mDnUOQsSNWvi3iOCbY90+Lv4NbonOQc33E4Gn/z5XX7tkftc84lWoH95qnHuZNe6pu3Sm4UW+dRy5VG/2rHFWpvklm5Vjnf1tcMuUz+w1Gv2pda+JE53+uH39c6h8LLtx9nfdvpfxG33zw871MkL1vGLzYON15yD/FXXznhfwrnLFI73N46w933PlnLl8qtQuYWj2l03f3RVXTvX2V34r3biS7L5/8zvhsf2DG5WU3r+rcn/NF6rmCu32cfJ6p3TzINVMVvHeoUdjc7Kvw1H863vdlT/75NCD3uvebrtbty+m0nqF1VZcmuh8lOAm5JHerWKX/y7nEbd6nyQ3wwntW7E3X+8PDu6X59r3y1Ib6QxvgWdwo7J+o5tDrNkjOSKnzg7ve0NqkI/lqKz8HOSoDXTFuOqE9p8TOTIzP8d3WmN8Nbb6g59TG62HfWxzOiVGo49ydCqH4/HVV74O8HSGeI/V0/HV535G8JQKxtvql/e/Dgbl5OSGqHo1wk74Mc1wrmxHWgcHs5nd35fKTkTe2iN47qLDp1aCZCRbbP9RQvw5+2J5RKGyRtWedsKLix/LJjdnZ2dfl3vwsx0z1hTVV4G4qy+GXra5av83RNbgW82RWAraS3rqSeshtBLXPrTGeBpLVHFr1rES3D22vpdG6ha21EtL2w4pvW32SdRppG5RS70aQ51G6pZ+9kzaetZp5C8Z1EdVp5G6Va1n0op6e9KkkbqVnw1HA6pX9FK3fAz1h27vIqhuK5At6anLKdQlPfXakvqaorpoq4eW1HNy1QVJeyNwHHUKqVs8jfqCorqVjdd5W51C6haOpV6Q23WL2sVN/qino6iftstWKKRuWVs98VV9NZI6hdStaqsLO+qCnnprFXJhR73ztY/+qlNI3fJR1DvPEYUNx13j0VDqCb2qQX/VxTjq3XBh+qw16aoXVtRjcrWiya5gexi6WdH0WWu8K7EeSj0kVysaTqU+feoWTaU+ff6SQv3DVeNB6FnonX7DMRtLPZLUUrdq1zbJUEUVkaSWulU79gXt1JOQSN3KqdSnT93yHRvhgxVVpJJa/lLsKH+wU09CQl3lj7SjPnXqJsZR7+tLK2rqm9HUp07dEoWx2EIVEYXULR5HvW/KnDp1CxXiLhulNATUI4Vo25L62g/1vqRo6tQtVUgvbdSTEEjdMoVFBUvqU6duFdQtq8971KfOWkuFFXMbpTQEstZcYZ/Ekrr0Q713J4+geuKHeqmwHWxJvSaoLmyoC3Lq1e6qFyulNAQmt8xf9VSpbw5fRUQgmovUBuPhS2mmT1/C6dSnzteTcdT7goWpV2mEWsw5fBURgYqSYhT1vpxo6nX43oXS3IJ6SC2O7Znd1iOpT7/JHE6lPn1VhRhDve7/ialtsK8tVJT0rXAvplfPJlKf3rwz69ioIyJZRdSd2W0U0/TsYZK4p6OyX0zTo74I6PV4G8U03XoFInft5dbVu1UqRK4UPbJeTNP9zgUNdTG+OplXv2S2K0o6Q+eainoyuvosoNjsNtTbsQKhd940X+xlo46oHSHSafStvKq2r07rRX6lVfXtRJjYG0vfu7yNOqJt9dOAFrHNipItdXqvaj0aSZ3iC3rv7Kk3V3lXAUFKa3VEjbX9RUCSO1vFNO/q1wFRfltS/7ePR9Y8CI6Llw6fWFKvVwFhxO2VHfXn3/RyFpBHWFC/q6+DwEP1ReAKUB+ynsQZoD5gPQnU6VNAfbiiCmfIoQ51qO9TT+IMA1eUbBxSH3ir9dEh9YHXJeeBrw97PXNJPTm/GI5VAAAAFDm5H4KZg+YDRXQb99wHi2q+O6de+RjFDh3PQR3qUPditWLjnPpgZYMPzqmLodbiHUxZk7NBuA4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAU/wGK2a+A3NJU1QAAAABJRU5ErkJggg==)

2020-06-12 15:48 UTC, bbeale commented
@mufeedvh Actually, the `Object.freeze()` approach was one of the first things I read when I initially started looking into this issue, but I wasn't sure if freezing the target or even just it's prototype would be overzealous for this project or have any other unwanted downstream impacts. It doesn't sound like that is an issue here, if I am understanding correctly, so I'll go ahead and add that to my PR when I get a chance this afternoon.

2020-06-13 18:17 UTC, bbeale commented
Hello sheriffs @toufik-airane @mufeedvh,

After reading up on prototype pollution and playing around with a few different solutions, it seems that `Object.freeze()` is indeed the better approach, so I have updated my PR to freeze the prototype of the target. 

I put the freeze call inside of `_assignHelper()` after the target is checked for null and is initialized as an Object. I did not notice a negative downstream impact this way, and it seemed safer to restrict prototype modification all around instead of just inside `merge()`. Right now, `merge()` spits out a console line where I previously had it throwing an exception. Please let me know if you think the check would be better off inside `merge()` itself.

Looking forward to more of your feedback!

2020-06-13 18:25 UTC, toufik-airane approved these changes
@bbeale thank you for your work. 👏

![huntr](https://img.shields.io/badge/LGTM-red?labelColor=black&link=https://www.huntr.dev&style=flat-square&label=&logo=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAfQAAAH0BAMAAAA5+MK5AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAFVBMVEVHcEzUTjrUSz7bUUXfTj/eTD3wWkwE37jxAAAABnRSTlMAOsPzjWJ73M2lAAAJoElEQVR42u2dS0PbOhBGLb/W4eU1hdbrtIDXAVKv01K8DjHo//+EC5RbHNsQSbHs0eg76yblRLI0I43kIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAECbg4OZl97H5/KZzU/v7JNcvlFf+2V+KBtc+WR+J7d49NbcI/dD2cGTPh/LHr74YC6KPvV65YF6JXt59LS7+9Hli4/Ua+5h3ZH8kCcfx7g3eI902SfmvEc6IT9l4Wujs272HY3O+Wk/2qXOd5AvpK/NHu00lw9M1fPd6kxDulgqcOpTyubD/CaV4DjQhWrqHAe6Uk1942EkxzeQj1TV+fX4XFW95maeSOlrj4/U1bn1+FJdnVmPF1L62uMjHXVePb7SUecV1UgtOMXxsZ76nJF6pjG+f/tzzmmJLtdo8noVCE+nNrnhtEgV6j3qnPp7pafOaYEu11TnM7EnUpe5p486p2bPtNXZPO25vjqT5XghDeARxscm6jwGutREnUdYU5qo8xjjCxN1ySGQT4zMWSzQhWbqaz8DGi7jXGmmvvF2lOMwzglDcwbjXGyq7n48l5qqu78H87o4VUsfk7eXAf7SZJR3f8P1WeJ76OUQL15OLuZeDvHh8zMb+jnER5uZYaM7H8VnC+OZ3fUh/l5/74VPFG8cyUrn1SNjdecTmFz6msB8sD51cbZcLu/vl8ubm/OC6+zWVfrx81drOPhzUzCc3Tr9/Wv/I/z3hh5OuZtQE3+VL3hN7Nv9vf716T++ZTWxV1oFQoecJvatDrx7oj7kox7rFoUdsYlpUu0t85JLTFNqX76SMCkrEQbD9REP9dhAQ/AI50KTOTpjoR6ZpCIJC/XUaJ7KOQTxqVE4nnHYY8+Mum7MSl0vOOGQumVm0XjOSF0z/awYZK2V2UObMmj1ymyCDhm1+lzvYzGjVtfMQxIGrZ6ZqQtG6gszdQ6T2wrqmuGcy4Fsul+re6geMEhaw/2GuTXUXSTeb16f+6eeMFqHN4zhFwzUDTO3lcPqgZl6xGG7MTeaoFMOm8ylUTCecaiIr/ZZm3O7oCTbZ0XW7VN+ZgMWi+Ixo0hWsCgZjE1imphBMPfegA8mT8nCafVgn53WmdvqucEUXfI4ClAZtCCTAyAGK/EJk2M/kf44FzEphzfYPquYHIIQ+nVEBZez+9olgwm7A08Puo+6+4e4tYtDSjZH91PNa9QEnwsbQk2VkM81HUKzQLhicrbx5LpxJc9K65d6HuCX7o7xJ+cvTV1q9fjo/ZaO52jocuWkeHL7t6kzrStHyvf62NcPuij/+/+mDnUOQsSNWvi3iOCbY90+Lv4NbonOQc33E4Gn/z5XX7tkftc84lWoH95qnHuZNe6pu3Sm4UW+dRy5VG/2rHFWpvklm5Vjnf1tcMuUz+w1Gv2pda+JE53+uH39c6h8LLtx9nfdvpfxG33zw871MkL1vGLzYON15yD/FXXznhfwrnLFI73N46w933PlnLl8qtQuYWj2l03f3RVXTvX2V34r3biS7L5/8zvhsf2DG5WU3r+rcn/NF6rmCu32cfJ6p3TzINVMVvHeoUdjc7Kvw1H863vdlT/75NCD3uvebrtbty+m0nqF1VZcmuh8lOAm5JHerWKX/y7nEbd6nyQ3wwntW7E3X+8PDu6X59r3y1Ib6QxvgWdwo7J+o5tDrNkjOSKnzg7ve0NqkI/lqKz8HOSoDXTFuOqE9p8TOTIzP8d3WmN8Nbb6g59TG62HfWxzOiVGo49ydCqH4/HVV74O8HSGeI/V0/HV535G8JQKxtvql/e/Dgbl5OSGqHo1wk74Mc1wrmxHWgcHs5nd35fKTkTe2iN47qLDp1aCZCRbbP9RQvw5+2J5RKGyRtWedsKLix/LJjdnZ2dfl3vwsx0z1hTVV4G4qy+GXra5av83RNbgW82RWAraS3rqSeshtBLXPrTGeBpLVHFr1rES3D22vpdG6ha21EtL2w4pvW32SdRppG5RS70aQ51G6pZ+9kzaetZp5C8Z1EdVp5G6Va1n0op6e9KkkbqVnw1HA6pX9FK3fAz1h27vIqhuK5At6anLKdQlPfXakvqaorpoq4eW1HNy1QVJeyNwHHUKqVs8jfqCorqVjdd5W51C6haOpV6Q23WL2sVN/qino6iftstWKKRuWVs98VV9NZI6hdStaqsLO+qCnnprFXJhR73ztY/+qlNI3fJR1DvPEYUNx13j0VDqCb2qQX/VxTjq3XBh+qw16aoXVtRjcrWiya5gexi6WdH0WWu8K7EeSj0kVysaTqU+feoWTaU+ff6SQv3DVeNB6FnonX7DMRtLPZLUUrdq1zbJUEUVkaSWulU79gXt1JOQSN3KqdSnT93yHRvhgxVVpJJa/lLsKH+wU09CQl3lj7SjPnXqJsZR7+tLK2rqm9HUp07dEoWx2EIVEYXULR5HvW/KnDp1CxXiLhulNATUI4Vo25L62g/1vqRo6tQtVUgvbdSTEEjdMoVFBUvqU6duFdQtq8971KfOWkuFFXMbpTQEstZcYZ/Ekrr0Q713J4+geuKHeqmwHWxJvSaoLmyoC3Lq1e6qFyulNAQmt8xf9VSpbw5fRUQgmovUBuPhS2mmT1/C6dSnzteTcdT7goWpV2mEWsw5fBURgYqSYhT1vpxo6nX43oXS3IJ6SC2O7Znd1iOpT7/JHE6lPn1VhRhDve7/ialtsK8tVJT0rXAvplfPJlKf3rwz69ioIyJZRdSd2W0U0/TsYZK4p6OyX0zTo74I6PV4G8U03XoFInft5dbVu1UqRK4UPbJeTNP9zgUNdTG+OplXv2S2K0o6Q+eainoyuvosoNjsNtTbsQKhd940X+xlo46oHSHSafStvKq2r07rRX6lVfXtRJjYG0vfu7yNOqJt9dOAFrHNipItdXqvaj0aSZ3iC3rv7Kk3V3lXAUFKa3VEjbX9RUCSO1vFNO/q1wFRfltS/7ePR9Y8CI6Llw6fWFKvVwFhxO2VHfXn3/RyFpBHWFC/q6+DwEP1ReAKUB+ynsQZoD5gPQnU6VNAfbiiCmfIoQ51qO9TT+IMA1eUbBxSH3ir9dEh9YHXJeeBrw97PXNJPTm/GI5VAAAAFDm5H4KZg+YDRXQb99wHi2q+O6de+RjFDh3PQR3qUPditWLjnPpgZYMPzqmLodbiHUxZk7NBuA4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAU/wGK2a+A3NJU1QAAAABJRU5ErkJggg==)

2020-06-15 23:23 UTC, mufeedvh approved these changes
Awesome work @bbeale! :tada::clap: 

![LGTM](https://img.shields.io/badge/LGTM-red?labelColor=black&link=https://www.huntr.dev&style=flat-square&logo=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAfQAAAH0BAMAAAA5+MK5AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAFVBMVEVHcEzUTjrUSz7bUUXfTj/eTD3wWkwE37jxAAAABnRSTlMAOsPzjWJ73M2lAAAJoElEQVR42u2dS0PbOhBGLb/W4eU1hdbrtIDXAVKv01K8DjHo//+EC5RbHNsQSbHs0eg76yblRLI0I43kIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAECbg4OZl97H5/KZzU/v7JNcvlFf+2V+KBtc+WR+J7d49NbcI/dD2cGTPh/LHr74YC6KPvV65YF6JXt59LS7+9Hli4/Ua+5h3ZH8kCcfx7g3eI902SfmvEc6IT9l4Wujs272HY3O+Wk/2qXOd5AvpK/NHu00lw9M1fPd6kxDulgqcOpTyubD/CaV4DjQhWrqHAe6Uk1942EkxzeQj1TV+fX4XFW95maeSOlrj4/U1bn1+FJdnVmPF1L62uMjHXVePb7SUecV1UgtOMXxsZ76nJF6pjG+f/tzzmmJLtdo8noVCE+nNrnhtEgV6j3qnPp7pafOaYEu11TnM7EnUpe5p486p2bPtNXZPO25vjqT5XghDeARxscm6jwGutREnUdYU5qo8xjjCxN1ySGQT4zMWSzQhWbqaz8DGi7jXGmmvvF2lOMwzglDcwbjXGyq7n48l5qqu78H87o4VUsfk7eXAf7SZJR3f8P1WeJ76OUQL15OLuZeDvHh8zMb+jnER5uZYaM7H8VnC+OZ3fUh/l5/74VPFG8cyUrn1SNjdecTmFz6msB8sD51cbZcLu/vl8ubm/OC6+zWVfrx81drOPhzUzCc3Tr9/Wv/I/z3hh5OuZtQE3+VL3hN7Nv9vf716T++ZTWxV1oFQoecJvatDrx7oj7kox7rFoUdsYlpUu0t85JLTFNqX76SMCkrEQbD9REP9dhAQ/AI50KTOTpjoR6ZpCIJC/XUaJ7KOQTxqVE4nnHYY8+Mum7MSl0vOOGQumVm0XjOSF0z/awYZK2V2UObMmj1ymyCDhm1+lzvYzGjVtfMQxIGrZ6ZqQtG6gszdQ6T2wrqmuGcy4Fsul+re6geMEhaw/2GuTXUXSTeb16f+6eeMFqHN4zhFwzUDTO3lcPqgZl6xGG7MTeaoFMOm8ylUTCecaiIr/ZZm3O7oCTbZ0XW7VN+ZgMWi+Ixo0hWsCgZjE1imphBMPfegA8mT8nCafVgn53WmdvqucEUXfI4ClAZtCCTAyAGK/EJk2M/kf44FzEphzfYPquYHIIQ+nVEBZez+9olgwm7A08Puo+6+4e4tYtDSjZH91PNa9QEnwsbQk2VkM81HUKzQLhicrbx5LpxJc9K65d6HuCX7o7xJ+cvTV1q9fjo/ZaO52jocuWkeHL7t6kzrStHyvf62NcPuij/+/+mDnUOQsSNWvi3iOCbY90+Lv4NbonOQc33E4Gn/z5XX7tkftc84lWoH95qnHuZNe6pu3Sm4UW+dRy5VG/2rHFWpvklm5Vjnf1tcMuUz+w1Gv2pda+JE53+uH39c6h8LLtx9nfdvpfxG33zw871MkL1vGLzYON15yD/FXXznhfwrnLFI73N46w933PlnLl8qtQuYWj2l03f3RVXTvX2V34r3biS7L5/8zvhsf2DG5WU3r+rcn/NF6rmCu32cfJ6p3TzINVMVvHeoUdjc7Kvw1H863vdlT/75NCD3uvebrtbty+m0nqF1VZcmuh8lOAm5JHerWKX/y7nEbd6nyQ3wwntW7E3X+8PDu6X59r3y1Ib6QxvgWdwo7J+o5tDrNkjOSKnzg7ve0NqkI/lqKz8HOSoDXTFuOqE9p8TOTIzP8d3WmN8Nbb6g59TG62HfWxzOiVGo49ydCqH4/HVV74O8HSGeI/V0/HV535G8JQKxtvql/e/Dgbl5OSGqHo1wk74Mc1wrmxHWgcHs5nd35fKTkTe2iN47qLDp1aCZCRbbP9RQvw5+2J5RKGyRtWedsKLix/LJjdnZ2dfl3vwsx0z1hTVV4G4qy+GXra5av83RNbgW82RWAraS3rqSeshtBLXPrTGeBpLVHFr1rES3D22vpdG6ha21EtL2w4pvW32SdRppG5RS70aQ51G6pZ+9kzaetZp5C8Z1EdVp5G6Va1n0op6e9KkkbqVnw1HA6pX9FK3fAz1h27vIqhuK5At6anLKdQlPfXakvqaorpoq4eW1HNy1QVJeyNwHHUKqVs8jfqCorqVjdd5W51C6haOpV6Q23WL2sVN/qino6iftstWKKRuWVs98VV9NZI6hdStaqsLO+qCnnprFXJhR73ztY/+qlNI3fJR1DvPEYUNx13j0VDqCb2qQX/VxTjq3XBh+qw16aoXVtRjcrWiya5gexi6WdH0WWu8K7EeSj0kVysaTqU+feoWTaU+ff6SQv3DVeNB6FnonX7DMRtLPZLUUrdq1zbJUEUVkaSWulU79gXt1JOQSN3KqdSnT93yHRvhgxVVpJJa/lLsKH+wU09CQl3lj7SjPnXqJsZR7+tLK2rqm9HUp07dEoWx2EIVEYXULR5HvW/KnDp1CxXiLhulNATUI4Vo25L62g/1vqRo6tQtVUgvbdSTEEjdMoVFBUvqU6duFdQtq8971KfOWkuFFXMbpTQEstZcYZ/Ekrr0Q713J4+geuKHeqmwHWxJvSaoLmyoC3Lq1e6qFyulNAQmt8xf9VSpbw5fRUQgmovUBuPhS2mmT1/C6dSnzteTcdT7goWpV2mEWsw5fBURgYqSYhT1vpxo6nX43oXS3IJ6SC2O7Znd1iOpT7/JHE6lPn1VhRhDve7/ialtsK8tVJT0rXAvplfPJlKf3rwz69ioIyJZRdSd2W0U0/TsYZK4p6OyX0zTo74I6PV4G8U03XoFInft5dbVu1UqRK4UPbJeTNP9zgUNdTG+OplXv2S2K0o6Q+eainoyuvosoNjsNtTbsQKhd940X+xlo46oHSHSafStvKq2r07rRX6lVfXtRJjYG0vfu7yNOqJt9dOAFrHNipItdXqvaj0aSZ3iC3rv7Kk3V3lXAUFKa3VEjbX9RUCSO1vFNO/q1wFRfltS/7ePR9Y8CI6Llw6fWFKvVwFhxO2VHfXn3/RyFpBHWFC/q6+DwEP1ReAKUB+ynsQZoD5gPQnU6VNAfbiiCmfIoQ51qO9TT+IMA1eUbBxSH3ir9dEh9YHXJeeBrw97PXNJPTm/GI5VAAAAFDm5H4KZg+YDRXQb99wHi2q+O6de+RjFDh3PQR3qUPditWLjnPpgZYMPzqmLodbiHUxZk7NBuA4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAU/wGK2a+A3NJU1QAAAABJRU5ErkJggg==)

2020-06-16 09:50 UTC, merged

2020-06-16 09:50 UTC, huntr-helper commented
Congratulations bbeale - your fix has been selected! 🎉

Thanks for being part of the community & helping secure the world's open source code.
If you have any questions, please respond in the comments section. Your bounty is on its way - keep hunting!

2020-06-16 10:44 UTC, huntr-helper commented
Congratulations bbeale - your fix has been selected! 🎉

Thanks for being part of the community & helping secure the world's open source code.
If you have any questions, please respond in the comments section. Your bounty is on its way - keep hunting!