Fixed Prototype Pollution
418sec/objutil pull request #3
Opened 2020-06-12 00:04 UTC by mufeedvh

### ⚙️ Description *

The fix is implemented by freezing the input `Object`'s `prototype`.

### 💻 Technical Description *

The function `merge()` function has 2 parameters `target` and `arg`. The `arg` parameter is being used to inject the prototype as per the PoC:

```javascript
var a = { x:1,y:{ w:1, z:2 }}
var malicious_payload = '{"__proto__":{"vulnerable":"Polluted"}}';
var {merge, remove} = require('objutil')
result = merge(a,JSON.parse(malicious_payload));
console.log({}.vulnerable);
```

These values (with the payload) is passed to the `merge()` function where it caused the prototype pollution, I used the `Object.freeze()` function to freeze the prototype just after accepting it which prevents further modification of the prototype.

**This fix is implemented with the help of this paper on Prototype Pollution:**

:spiral_notepad: [Prototype pollution attack in NodeJS application](https://github.com/HoLyVieR/prototype-pollution-nsec18/blob/master/paper/JavaScript_prototype_pollution_attack_in_NodeJS.pdf)

**From Mitigation Methods -> Freezing the prototype (from the paper):**
> The ECMAScript standard version 5 introduced a very interesting set of functionality to the
> JavaScript language. It allowed the definition of non-enumerable property, getter, setter and
> a lot more. One of API introduced was “Object.freeze”. When that function is called on an
> object, any further modification on that object will silently fail. Since the prototype of “Object”
> is an object, it’s possible to freeze it. Doing so will mitigate almost all the exploitable case.

### 🐛 Proof of Concept (PoC) *

```javascript
var a = { x:1,y:{ w:1, z:2 }}
var malicious_payload = '{"__proto__":{"vulnerable":"Polluted"}}';
var {merge, remove} = require('objutil')
result = merge(a,JSON.parse(malicious_payload));
console.log({}.vulnerable);
```

### 🔥 Proof of Fix (PoF) *

```javascript
function merge(target, arg) { // length==2
  // freezing the prototype to prevent prototype pollution
  Object.freeze(arg.prototype)
  return _assignHelper(target, arguments, function (a, b, key, path) {
    var bval = b[key]
    if (bval !== undefined && isPrimitive(bval)) a[key] = bval
    else if (!(key in a)) a[key] = isArray(bval) ? [] : isPOJO(bval) ? {} : bval
  })
}
```

`Object.freeze()` fixes this issue by not allowing modifications to the Object's prototype as mentioned above.

### 👍 User Acceptance Testing (UAT)

    $ node test/test.js

It doesn't introduce any breaking changes as the only further addition is an `Object.freeze()` function.

### 📊 Metadata *

#### Bounty URL: https://www.huntr.dev/app/bounties/open/1-npm-objutil

2020-06-12 10:25 UTC, toufik-airane requested changes
Dear @mufeedvh,

**The Object.freeze() mitigation is totally broken and ineffective in the merge() function.**
Indeed, the merge function explicitly assigns the value to a key, that method overrides the freeze protection.

**test/test.js**
```javascript
'use strict'

var assert = require('assert')
var expect = require('chai').expect
var lib = require('../dist/objutil.cjs.js')

var a, b, c
var newObj = function (obj) {
  return JSON.parse(JSON.stringify(obj))
}

var a = { x: 1, y: { w: 1, z: 2 } }
var malicious_payload = '{"__proto__":{"vulnerable":"Polluted"}}';
var result = lib.merge(a, JSON.parse(malicious_payload));
console.log({}.vulnerable);
```

```bash
objutil [master] ⚡  yarn build && node test/test.js
👉 Polluted
```

2020-06-12 10:42 UTC, toufik-airane commented
For the record,

We can't freeze the attribute of an object.
```
> a
{ a: 'b' }
> Object.freeze(a.a)
'b'
> a
{ a: 'b' }
> a["a"] = "c"
'c'
> a
{ a: 'c' }
```

We can only freeze the entire object
```
> a
{ a: 'c' }
> Object.freeze(a)
{ a: 'c' }
> a
{ a: 'c' }
> a["a"] = "d"
'd'
> a
{ a: 'c' }
```
And that's an issue for a merge function.

2020-06-15 23:19 UTC, mufeedvh commented
Yeah true, I didn't think about that. And I am closing this PR as https://github.com/418sec/objutil/pull/1 is a good fix! :raised_hands:

2020-06-15 23:19 UTC, closed without merging

2020-06-15 23:19 UTC, huntr-helper commented
Sorry mufeedvh, we enjoyed reviewing your fix but it has not been selected this time. If this bounty has not been closed, please feel free to try again with a new pull request!
        
We appreciate your effort and look forward to reviewing more of your fixes in the future! 🔨😎